name: PublishApp

on:
  workflow_dispatch:
  push:
    branches:
      - Release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./EmployeMS.sln

      - name: Build
        run: dotnet build ./EmployeMS.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./EmployeMS.sln --configuration Release --no-build
